fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    augeasproviders_core: git://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_grub: git://github.com/hercules-team/augeasproviders_grub.git
  symlinks:
    kdump: "#{source_dir}"
